stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: everledgerio/evl-ui-components
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
