image: docker:stable
pipelines:
  branches:
    master:
      - step:
          name: build and deploy
          
          script:
            - set -eu
            - apk add --no-cache py-pip bash curl
            - chmod 755 push-docker-image-to-registry.sh
            - ./push-docker-image-to-registry.sh $BITBUCKET_BUILD_NUMBER
            - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            - chmod +x ./kubectl
            - mv ./kubectl /usr/local/bin/kubectl
            - echo $KUBE_TOKEN | base64  -d > ./kube_token
            - echo $KUBE_CA | base64 -d > ./kube_ca
            - kubectl config set-cluster devx2 --server=https://34.68.45.155 --certificate-authority="$(pwd)/kube_ca"
            - kubectl config set-credentials default --token="$(cat ./kube_token)"
            - kubectl config set-context development --cluster=devx2 --user=default
            - kubectl config use-context development
           # - kubectl get nodes
            - kubectl set image deployment/evl-ui-components evl-ui-components=everledgerio/evl-ui-components:$BITBUCKET_BUILD_NUMBER --namespace devops
          services:
            - docker
definitions:
  services:
    docker:
      memory: 2048 