apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-b7g5h
    field.cattle.io/publicEndpoints: '[{"addresses":["35.193.106.243"],"port":31240,"protocol":"TCP","serviceName":"devops:evl-ui-components-nodeport","allNodes":true},{"addresses":["35.193.106.243"],"port":32575,"protocol":"TCP","serviceName":"devops:ingress-b8b7494307c89e8b53bed64b8141bb36","allNodes":true},{"addresses":["34.102.178.26"],"port":443,"protocol":"HTTPS","serviceName":"devops:ingress-b8b7494307c89e8b53bed64b8141bb36","ingressName":"devops:evl-ui","hostname":"evl-ui.devx2.playground.everledger.io","allNodes":false}]'
  creationTimestamp: "2020-01-23T08:18:26Z"
  generation: 8
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-devops-evl-ui-components
  name: evl-ui-components
  namespace: devops
  selfLink: /apis/apps/v1beta2/namespaces/devops/deployments/evl-ui-components
  uid: ee15f0db-3db8-11ea-9322-42010a800039
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-devops-evl-ui-components
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-01-23T08:18:25Z"
        field.cattle.io/ports: '[[{"containerPort":6006,"dnsName":"evl-ui-components-nodeport","kind":"NodePort","name":"6006tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-devops-evl-ui-components
    spec:
      containers:
      - image: everledgerio/evl-ui-components:latest
        imagePullPolicy: Always
        name: evl-ui-components
        ports:
        - containerPort: 6006
          name: 6006tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30